language: python
python: 2.7

services:
 - redis

# Setup a test database
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres


# Setup environment variables
env:
  - DATABASE_URL="postgresql://postgres:@localhost/travis_ci_test" TEST_DATABASE_URL="postgresql://postgres:@localhost/travis_ci_test" SECRET_KEY="1234567890" TEST_REDIS_URL=redis://localhost:6379 REDISCLOUD_URL=redis://localhost:6379

# Install dependencies
install: "pip install -r requirements.txt"

# Run tests
script: py.test
