language: python
python: 2.7

# Setup a test database
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# Setup environment variables
env:
  - TEST_DATABASE_URL='postgres://postgres:@localhost/travis_ci_test' SECRET_KEY='1234567890'

# Install dependencies
install: "pip install -r requirements.txt"

# Run tests
script: py.test
